[build]
builder = "nixpacks"
buildCommand = "npm install --workspaces"

[deploy]
startCommand = "echo 'This is a monorepo. Deploy frontend or backend separately.'"

[[services]]
name = "frontend"
rootDirectory = "frontend"
buildCommand = "npm ci && npm run build"
startCommand = "npm run serve"

[[services]]
name = "backend"
rootDirectory = "backend"  
buildCommand = "npm ci"
startCommand = "node server.js"