[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm ci && npm run build"

[deploy]
startCommand = "cd frontend && npm run serve:production"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Environment variable configuration
[env]
NODE_ENV = "production"
PORT = "5000"

[[services]]
name = "frontend"
rootDirectory = "frontend"

[services.frontend.build]
buildCommand = "npm ci && npm run build"

[services.frontend.deploy]
startCommand = "npm run serve:production"

[[services]]
name = "backend"
rootDirectory = "backend"

[services.backend.build]
buildCommand = "npm ci"

[services.backend.deploy]
startCommand = "npm start"